---
# HTCondor's semantic versioning syntax
# Major version values:
#   9
#   10
#   23
# Series (former name)
#   0   (stable)    - just bug fixes
#   x   (current)   - minor feature additions & bug fixes
major_version: 23
series: x
htcss_version: "{{ major_version }}.{{ series }}"

# The configuration flags for a nodes role in the pool
htcondor_role_manager: false
htcondor_role_access: false
htcondor_role_execute: false

# Configuration for using a Shared File-System
# https://htcondor.readthedocs.io/en/latest/admin-manual/configuration-macros.html#shared-file-system-configuration-file-macros
# https://htcondor.readthedocs.io/en/latest/users-manual/submitting-a-job.html#submitting-jobs-using-a-shared-file-system
shared_fs_domain: ""

# The (DNS or IPv*) address for the central-manager
cm_host_address: ""

# The pool password (preferably stored in an encrypted secrets file)
htcss_pool_password: changeme
